# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.pcc.qedm
canonical: https://profiles.ihe.net/PCC/QEDm
version: 0.0.1-current
name: IHE_PCC_QEDm
title: "Query for Existing Data for Mobile (QEDm)"
description: The Query for Existing Data for Mobile Profile (QEDm) supports dynamic queries for clinical data elements, including observations, allergy and intolerances, problems, diagnostic results, medications, immunizations, procedures, encounters and provenance by making the information widely available to other systems within and across enterprises to support provision of better clinical care. It defines a transaction used to query a list of specific data elements, persisted as FHIR resources.
releaseLabel: ci-build
#releaseLabel: Trial-Implementation
#date: 2022-01-02
status: active
publisher:
  - name: IHE Patient Care Coordination Technical Committee
  - url: https://www.ihe.net/ihe_domains/patient_care_coordination/
  - email: pcc@ihe.net
contact:
  - name: IHE Patient Care Coordination Technical Committee
    telecom:
      - system: email
        value: pcc@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+

dependencies:
  ihe.iti.mhd: 
    id: iheitimhd
    version: 4.2.1 
  ihe.iti.pdqm: 
    id: ihepdqm
    version: 2.4.0
  ihe.iti.pixm:
    id: iheitipixm
    version: 3.0.3
  ihe.iti.mcsd:
    id: iheitimcsd
    version: 3.8.0
  ihe.formatcode.fhir:
    id: iheformatcodefhir
    version: 1.1.0
  ihe.iti.balp:
    id: iheitibasicaudit
    version: 1.1.2
  ihe.iti.svcm:
    id: iheitisvcm
    version: 1.5.1
  ihe.iti.mxde:
    uri: https://profiles.ihe.net/ITI/mXDE/ImplementationGuide/ihe.iti.mxde
    version: 1.3.0
# TODO likely other dependencies

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: Query for Existing Data for Mobile (QEDm)
    generation: markdown
  volume-1.md:
    title: 1:X Query for Existing Data for Mobile (QEDm)
    generation: markdown
  PCC-44.md:
    title: 2:3.44 Mobile Query Existing Data [PCC-44]
    generation: markdown
  volume-4.md:
    title: Volume 4 - National Extensions
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: Significant Changes & Issues
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  downloads.md:
    title: Downloads and Analysis
    generation: markdown
    
menu:
  QEDm Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#actors-and-transactions
    Actor Options: volume-1.html#actor-options
    Required Groupings: volume-1.html#required-groupings
    Overview: volume-1.html#overview
    Security Considerations: volume-1.html#security-considerations
    Cross-Profile Considerations: volume-1.html#other-grouping
  Volume 2:
    "Mobile Query Existing Data [PCC-44]": PCC-44.html
  Volume 4: volume-4.html
  Artifacts: artifacts.html
  Other:  
    Test Plan: testplan.html    
    Changes to Other IHE Specifications: other.html
    Downloads and Analysis: downloads.html

